const GET_PROMO_LOADING = "GET_PROMO_LOADING";
const GET_PROMO_SUCCESS = "GET_PROMO_SUCCESS";
const GET_PROMO_ERROR = "GET_PROMO_ERROR";
const FLUSH_PROMO = "FLUSH_PROMO";

export default { GET_PROMO_LOADING, GET_PROMO_SUCCESS, GET_PROMO_ERROR, FLUSH_PROMO };
