const GET_COURSE_LOADING = "home/GET_COURSE_LOADING";
const GET_COURSE_ERROR = "home/GET_COURSE_ERROR";
const GET_COURSE_SUCCESS = "home/GET_COURSE_SUCCESS";

export default {
    GET_COURSE_LOADING,
    GET_COURSE_ERROR,
    GET_COURSE_SUCCESS
};
