const GET_NEWS_LOADING = "GET_NEWS_LOADING";
const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
const GET_NEWS_ERROR = "GET_NEWS_ERROR";
const FLUSH_NEWS = "FLUSH_NEWS";

export default { GET_NEWS_LOADING, GET_NEWS_SUCCESS, GET_NEWS_ERROR, FLUSH_NEWS };
